'use strict';
const modal = document.querySelector('.modal');
const overLay = document.querySelector('.overlay');
const btnOpenModal = document.querySelectorAll('.show-modal');
const btnCloseModal = document.querySelector('.close-modal');

console.log(btnOpenModal);

//adding event listsner to the buttons
for (let i = 0; i < btnOpenModal.length; i++)
  //console.log(btnOpenModal[i].textContent);
  btnOpenModal[i].addEventListener('click', () => {
    console.log('Button Clicked');
    modal.classList.remove('hidden');
    overLay.classList.remove('hidden');
  });

//create a function closeModal
function closeModal() {
  modal.classList.add('hidden');
  overLay.classList.add('hidden');
}
btnCloseModal.addEventListener('click', closeModal);
overLay.addEventListener('click', closeModal);

//handling keys
//keys are global events; happens anywhere in the document
//keydown; press and release any key
//keypress; press and hold onto a key
//keyup; when the key is released
//specify they key to press
//figuring out which key was pressed requires us to look at the event object. When any key is pressed, an event object is generated by javascript, we can pass that event as a parameter in the function that is passed after the keyboard event. When  we console.log the event we get an event object with the key that was pressed
document.addEventListener('keydown', event => {
  console.log(event.key);

  //ensuring that the even occurs only if the Esc key is pressed down
  if (event.key === 'Escape' && !modal.classList.contains('hidden')) {
    //confirm if the div to be closed does not contain class hidden
    // if (!modal.classList.contains('hidden')) {
    //   //call closeModal function
    closeModal();
    //}
  }
});
